### ISSUE TITLE
GitHub Actions初使用

### ISSUE THREAD

**Issue by xlzy520** [xlzy520/blog#50]
[ pixiv: 520]: # 'https://i0.hdslb.com/bfs/album/a707edf425f0bf5ec557d687e4ef45fa6c82eada.jpg'

最近用上了GitHub Actions， 发现还真的挺好用的，不仅有自动部署，还有定时器定时执行脚本，妥妥的骚东西呀。

### 自动部署
在项目中创建.github文件夹，然后创建workflows文件夹，再在里面创建ci.yml
```yml
name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: run deploy.sh
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.github_actions_access_token }} # toKen私密变量
        run: npm install && npm run deploy

```

其中`secrets.github_actions_access_token`后面部分是你在GitHub上定义的私有属性

如
![image](https://user-images.githubusercontent.com/28336270/78855637-043be900-7a57-11ea-9f9d-8f328f126f24.png)

触发`on`对应的行为后，GitHub就会自动构建部署。

### 骚操作
比如定时器记录网易云每日推荐歌单，或者提醒，定时执行脚本能做的，都可以想象一下

[利用GithubActions自动备份网易云音乐每日推荐歌曲](https://segmentfault.com/a/1190000021188929?utm_source=tag-newest)
