### ISSUE TITLE
利用GitHub Action自动release我的Chrome插件压缩包

### ISSUE THREAD

**Issue by xlzy520** [xlzy520/blog#64]
[ pixiv: 520]: # 'https://i0.hdslb.com/bfs/album/a707edf425f0bf5ec557d687e4ef45fa6c82eada.jpg'

写了一个哔哩哔哩的图床插件，但是每次发版都需要自己手动构建，然后压缩再传到GitHub Release上，觉得好麻烦啊。之前我已经尝试过自动构建并发布到GitHub Pages了，那这次肯定要发布到release上了呗。

### 配置
1. 创建`.github`文件夹，然后创建`workflows`文件，最后创建`release.yml`文件
2. `release.yml`文件内容如下
```yml
name: release

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - "*"   #监听push tag的时候执行构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "build and zip"    # 先build，然后压缩dist为压缩包
        run: |
          npm install && npm run build:pro
          zip -r bilibili.zip dist
      - uses: xresloader/upload-to-github-release@master   # 使用第三方Action发布
        env:
          GITHUB_TOKEN: ${{ secrets.A }}
        with:
          file: "*.zip;"   # 要发布的匹配的文件
          delete_file: ""
          tags: true
          draft: false
          prerelease: false  # 是否是prerelease
          overwrite: true
          verbose: true

```

3. 在项目的setting里配置`secrets`，否则会报无权限
4. 推送代码，然后可以尝试push一个带tag的commit，进入Action页面，会找一个构建job
5. job执行完成之后，可以在release页面找到这个release包，带上了我们需要的zip

### 参考
[尝鲜Github Action](https://zhuanlan.zhihu.com/p/83588358)
