### ISSUE TITLE
CSS画一个梯形，内部再加一个三角形

### ISSUE THREAD

**Issue by xlzy520** [xlzy520/blog#66]
[ pixiv: 520]: # 'https://i0.hdslb.com/bfs/album/a707edf425f0bf5ec557d687e4ef45fa6c82eada.jpg'
突然想要玩玩

### preview
![image](https://user-images.githubusercontent.com/28336270/98905919-320a7400-24f7-11eb-9a4a-b19fbfb0b094.png)

![image](https://user-images.githubusercontent.com/28336270/98906969-012b3e80-24f9-11eb-9cfb-436d13753645.png)

### Code
```html
        <div class="org-collapse">
          <div class="org-collapse-box" @click="collapse">
            <div class="arrow"></div>
          </div>
        </div>
```

```scss
  .org-collapse{
    display: flex;
    align-items: center;
    .org-collapse-box{
      cursor: pointer;
      /*width: 100px;*/
      height: 100px;
      border-top: 20px solid transparent;
      border-right: 20px solid transparent;
      border-bottom: 20px solid transparent;
      border-left: 20px solid red;
      display: flex;
      align-items: center;
      .arrow{
        width: 40px;
        height: 0px;
        border-top: 10px solid transparent;
        border-right: 10px solid #eee;
        border-bottom: 10px solid transparent;
        border-left: 10px solid transparent;
        margin-left: -45px;
     &.right{
          border-top: 10px solid transparent;
          border-right: 10px solid transparent;
          border-bottom: 10px solid transparent;
          border-left: 10px solid #eee;
          margin-left: -15px;
        }
      }
    }
  }

```
